workspace = { members = ["model_traits_macro"] }
[package]
name = "instructor-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
tokio = {version = "1.36.0", features = ["full"]}

serde = "1.0.197"
serde_json = "1.0.115"
schemars = "0.8.16"
validator = { version = "0.16", features = ["derive"] }
<<<<<<< Updated upstream
=======
>>>>>>> Stashed changes
syn = {version = "2.0.55", features = ["full"]}
model_traits_macro = { path = "./model_traits_macro" }
<<<<<<< Updated upstream
tiktoken-rs = "0.5.8"
async-openai = "0.20.0"
futures = "0.3.30"
thiserror = "1.0.58"
rand = "0.8.5"
openai-api-rs = "4.0.8"
derive_builder_macro = "0.20.0"
derive_builder = "0.20.0"
=======
tiktoken-rs = "0.5.8"
async-openai = "0.20.0"
futures = "0.3.30"
thiserror = "1.0.58"
rand = "0.8.5"
openai-api-rs = "4.0.8"
derive_builder_macro = "0.20.0"
derive_builder = "0.20.0"
>>>>>>> Stashed changes


